/*
 * Copyright 2003-2005 (c) Live Media Pty Ltd. <argot@einet.com.au> 
 *
 * This software is licensed under the Argot Public License 
 * which may be found in the file LICENSE distributed 
 * with this software.
 *
 * More information about this license can be found at
 * http://www.einet.com.au/License
 * 
 * The Developer of this software is Live Media Pty Ltd,
 * PO Box 4591, Melbourne 3001, Australia.  The license is subject 
 * to the law of Victoria, Australia, and subject to exclusive 
 * jurisdiction of the Victorian courts.
 */
package com.argot;

/**
 * Any exception generated by the Type system is of this type.
 */
public class TypeException
extends Exception
{
	private static final long serialVersionUID = 4489198449670172634L;

	public TypeException( String reason )
	{
		super( reason );
	}
	
	public TypeException( String reason, Throwable cause )
	{
		super( reason, cause );
	}
}
